- modules/download.py
- modules/upload.py
Now download a big file to Ur server and upload it to the easily
> Upload and Download plug added

- modules/pmpermit.py
Bots will now be ignored from pmpermit or else they used to spam us and even some bots ban us forever 😑
> Bot Filter added 😶

- userbot/modules/misc.py
Your code was no able to get the id of the original sender of a forwarded message, also without a check if the message is a reply will spam the terminal with NoneTypes if you don't reply to a message (`fixed with if message`)
And a suggestion: change it to .id and if is not a reply to send the chat id
> Improve userID getter

- userbot/__init__.py
- userbot/__main__.py
- userbot/modules/QRCode.py
- userbot/modules/__init__.py
- userbot/modules/admin.py
- userbot/modules/afk.py
- userbot/modules/download.py
- userbot/modules/evaluators.py
- userbot/modules/filter.py
- userbot/modules/get_admin.py
- userbot/modules/memes.py
- userbot/modules/misc.py
- userbot/modules/notes.py
- userbot/modules/pmpermit.py
- userbot/modules/profile.py
- userbot/modules/purge.py
- userbot/modules/scrapers.py
- userbot/modules/screencapture.py
- userbot/modules/sed.py
- userbot/modules/spammer.py
- userbot/modules/sql_helper/__init__.py
- userbot/modules/sql_helper/filter_sql.py
- userbot/modules/sql_helper/notes_sql.py
- userbot/modules/sql_helper/pm_permit_sql.py
- userbot/modules/sql_helper/spam_mute_sql.py
- userbot/modules/web_server_stats.py
The code was automatically beautified!!
> Beautify the code

- userbot/modules/notes.py
- userbot/modules/sql_helper/notes_sql.py
Improved the code from the `notes.py` and `notes_sql.py`:
- Notes now save with their markdown format and newlines without causing any format issues when getting them
- `.rmnotes` now purges all the notes in a specific chat
- If there's no notes to purge in a specific chat the user will know by editing his message.
> Improved the note module

- Aptfile
- userbot/__init__.py
- userbot/modules/package.py
This will install any system packages (neofetch for example) when the bot starts.
> Automated system packages installation

- init/init_script.sh
> [FIXUP] : [Autoinstall Script] : Fix the mess

- sample_config.env
- userbot/__init__.py
- userbot/modules/misc.py
Added dogbin to the paste command, added support for dogbin shortened URLs and added get_dogbin_content command.
Credits:
@deletescape for dogbin(Thx!) and Python implelemtation in SkittBot
> Dogbin support for paste, updater toggling

- userbot/modules/purge.py
> modules: purge: *inhales* follow another ducking telethon changes

- userbot/modules/kang.py
You can add support for kanging stickers later as well
> userbot: add kang support

- userbot/modules/kang.py
also handle all other types of images. 
Current implementation supports using sticker's emoji as well.
Finally, remove unused imports.
dev pls merge
> userbot: kang: Add stickers support

- userbot/modules/kang.py
the if condition threw an exception if you didn't reply to a message and caused a memory leak.
P.S before merging please do test in heroku ASAP because i use GCP!
> userbot: kang: fix memory spikes in heroku

- userbot/modules/kang.py
rebase later deb. This is a continuation of PR #44
> userbot: kang: handle all the exceptions properly

- .gitignore
- init/init_script.sh
Script will now track its progress.. and save its progress between checkpoints
incase of any error.. script will then resume from the last saved task.. instead of running all stuffs again
morever.. if any user still wants to run script from start... init_script.sh --reset will clear all saved progress
> init_script: track progress of the script

- requirements.txt
- userbot/modules/memes.py
all cowsay characters work. i.e .tuxsay .cheesesay .daemonsay etc
> add universal cowsay

- userbot/modules/system_stats.py
Fixed holder name and removed function to change header as asked before. Also pushing to the right branch this time.
> Update system_stats to change user for alive

- userbot/modules/notes.py
- userbot/modules/scrapers.py
> userbot: modules: notes, scrapers: Fix some small issues

- userbot/modules/purge.py
cuz delmsg is long and since we are lazy, so let's nuke it and be happy.
> modules/purge.py: delmsg > del

- userbot/modules/kang.py
- userbot/modules/purge.py
- userbot/modules/time.py
* Added country-code support to time.py
* Fixed a bug which caused errors in purge.py
* Changed some strings to be Upper-case in kang.py
> userbot: modules: kang, purge, time: edit things

- userbot/modules/time.py
it should be capital i, not small l
> module: time: fix typo in time format

- userbot/modules/time.py
What's Tested:
Normal case
small case
mix of capital and small
Above conditions apply to all countries available, whether one word or two
No extra exceptions/errors from this
> modules/time.py: Fix case sensitiveness

- userbot/modules/kang.py
I forgot to stage the change in #58 apparently
> userbot: kang: fix kanging of files

- userbot/modules/scrapers.py
It would only search the first word of the string and throw a syntax error while using some characters before.
> Fix .google's search string

- userbot/modules/evaluators.py
* Fixed the wrong use of isinstance() which returned to an exception.
* Fixed the wrong else block identation which allowed /eval, #eval and others to be executed.
* Fixed eval not sending the evaluation as a file when it was exactly 4096 characters.
* Fixed eval deleting an nonexisting file if the output was larger than 4095 characters.
* Fixed eval throwing an exeption when no expression was given.
* Fixed eval trying to send the output file even if the evaluation was not larger than 4095 characters.
* Eval now returns the exception thrown by the evaluation.
* And more...
> modules: evaluators: Fix lots of eval issues

- userbot/modules/admin.py
- userbot/modules/afk.py
- userbot/modules/chatid.py
- userbot/modules/dogbin.py
- userbot/modules/download.py
- userbot/modules/evaluators.py
- userbot/modules/filter.py
- userbot/modules/get_admin.py
- userbot/modules/kang.py
- userbot/modules/misc.py
- userbot/modules/mute_chat.py
- userbot/modules/notes.py
- userbot/modules/pmpermit.py
- userbot/modules/purge.py
- userbot/modules/qrcode.py
- userbot/modules/scrapers.py
- userbot/modules/screencapture.py
- userbot/modules/sed.py
- userbot/modules/system_stats.py
- userbot/modules/time.py
- userbot/modules/upstream.py
- userbot/modules/userdata.py
- userbot/modules/whois.py
- userbot/modules/www.py
Fixed exec, pip, random, yt_dl(due to a group mismatch) and some functions in userdata.py which weren't working before.
Changed afk a bit so it won't make a new line before and after the reason.
Added almost all the commands to .help as well.
> Fixed and added a few things.

- userbot/modules/memes.py
- userbot/modules/mute_chat.py
- userbot/modules/notes.py
- userbot/modules/scrapers.py
* Clean up some memes code, fix -_-.
* Transition to complete regex patterns in memes.
* Minor changes in mute_chat.
* Fix some notes commands being executed with "/", "#", "@", "!".
* Fix lang command not telling it changed the language successfully.
* Some changes to trt and tts logic.
> userbot: modules: memes, mute_chat, notes, scrapers: cleanups and bug fixes

- userbot/__init__.py
- userbot/modules/afk.py
- userbot/modules/purge.py
- userbot/modules/time.py
- userbot/modules/weather.py
Added weather command to get current weather details from open weather map.
Fixed purgeme so it doesn't delete everyone's messages if user is an admin.
For time.py, just added constants in holder and the rest is minor string changes.
> Added .weather and fixed .purgeme

- userbot/modules/evaluators.py
- userbot/modules/scrapers.py
- userbot/modules/weather.py
Fixed functions where they wouldn't send a file if output was over the limit.
Added exceptions in most of them.
Title's for yt search get decoded now.
Rest are just very minor fixes/changes.
> Fixed some functions in scrapers.py and some minor fixes for rest

- userbot/modules/get_admin.py
delusers is a module.. which will help you keep your groups clean
it searches for deleted accounts.. and also removes them
usage:
.delusers [searches for deleted acc]
.delusers clean [searches and removes deleted acc]
> module: add delusers

- Dockerfile
> Fix Dockers cloning branch

- userbot/modules/admin.py
- userbot/modules/evaluators.py
- userbot/modules/whois.py
* Admin modules now allow arguments(id or mention) besides replying
* All of the Admin commands log in the logger group
* All of the Admin commands use regex pattern groups
* Whois cleanups, get_user function reworked
* Fixed lots of indentation issues in evaluators.py which caused bugs
* Evaluator commands aren't permitted to do dangerous operations such as "cat config.env"
* Term command now checks for not permitted characters("/", "#", "@", "!")
* All of the evaluators commands now use regex pattern groups
* Fix a typo in text file name in evaluators
> modules: admin, evaluators, whois: fixups, add arguments in admin.py modules

- userbot/modules/admin.py
- userbot/modules/download.py
- userbot/modules/evaluators.py
- userbot/modules/get_admin.py
- userbot/modules/help.py
- userbot/modules/memes.py
- userbot/modules/qrcode.py
- userbot/modules/scrapers.py
- userbot/modules/system_stats.py
- userbot/modules/time.py
- userbot/modules/updater.py
- userbot/modules/weather.py
- userbot/modules/whois.py
* All of the modules(which have the need for it) now use new regex patterns
* Small changes in admin module logger messages
* Fixed the userbot trying to delete the replied messages when banning without replying
* Fix translator emoji bug
>  treewide: modules: fix translator emoji bug, new regex patterns, more

- userbot/modules/download.py
- userbot/modules/filter.py
- userbot/modules/memes.py
- userbot/modules/notes.py
- userbot/modules/pmpermit.py
- userbot/modules/scrapers.py
- userbot/modules/spotify.py
- userbot/modules/userdata.py
- userbot/modules/weather.py
- userbot/modules/www.py
- Fixed the list for .uploadir command in **download**.
- Added exception in approve so it doesn't make the log ugly if key already exists in database and some fixes where user's link won't always work in logger group's message in **pmpermit**
- Plyint was showing a warning for youtube variable, so reverted it in **scrapers**
- Added extra string in .filters so, it'll show if there aren't any filters in **filter**, and minor string changes for .saved in **notes**
- Added more info for weather result in **weather**
- Added missing prefix checks in .clap and .bt in **memes**
- Pattern edit for .enablespotify and .disablespotify in **spotify**
- Moonscape pong message in **www**
> Bloat weather because why not and some minor fixes

- userbot/modules/welcomes.py
* Cleaned up the code(from pylint -8.5 score to 9.56)
* Fixed up some bugs such as using loop variable outside the loop
* Remove unnecessary imports
* Extend the algorithm by adding Announcements Bot name to the list
* Add helper to the module
* Fix the logger logic(the module now checks if logger is enabled or not)
> modules: welcome_mute: cleanups, extend the algorith, fix bugs

- requirements.txt
- requirementsDOCKER.txt
- userbot/modules/scrapers.py
> modules: scrapers: Fix Translator for non-Latin textx

- requirementsDOCKER.txt
- userbot/events.py
- userbot/modules/afk.py
- userbot/modules/filter.py
- userbot/modules/notes.py
- userbot/modules/pmpermit.py
Anti-Abuse of Filters, AFK and Notes. Also updated requirements.
Well it's tested :P
> Anti-Abuse of Filters, AFK and Notes. Also updated requirements

- userbot/modules/admin.py
* Added 'pin' command, which allows any admin to pin messages easily. The userbot pins messages silent by default, but there is a 'loud' argument for pinning loudly.
* Added 'kick' command, allowing admins to kick any user from the group with the userbot.
* Also done some changes in get_user function:
1. Added a new get_user_from_id function. This allows to get user entity from its ID.
2. Renamed the previous get_user command to get_user_from_event for better understanding of its purpose.
> modules: admin: Add 'kick' and 'pin' commands

- userbot/events.py
- userbot/modules/admin.py
- userbot/modules/afk.py
- userbot/modules/evaluators.py
- userbot/modules/filter.py
- userbot/modules/memes.py
- userbot/modules/notes.py
- userbot/modules/pmpermit.py
- userbot/modules/scrapers.py
Removed noabuse decorator, can use register like before with "disable_edited" argument to not receive updates from edited messages.
Clean-up and fixes for cowsay, trt, pin and kick.
> Code clean-up and some minor fixes

- userbot/modules/whois.py
Also added Is bot, isRestricted and is verified
> Fixed whois broken on peeps missing a Pfp

- userbot/modules/help.py
for easier copy pasta in case user wants to do .help <module_name>
> make each item in help section in monospace font

- Dockerfile
- userbot/modules/chat.py
- userbot/modules/dogbin.py
- userbot/modules/misc.py
- userbot/modules/pmpermit.py
- userbot/modules/system_stats.py
- userbot/modules/welcomes.py
Signed-off-by: Kandarp <Kandnub@gmail.com>
- Allow userbot to auto approve people if the first message is sent by their id in private chats.
- Fix pip not sending result larger than 4096 characters.
- Make the userbot ignore the bots added by an admin in welcome_mute
- Fix paste and get_dogbin_content regex patterns.
- Proper error handling in get_dogbin_content.
- Allow .log to log messages without a reply.
- Update branch for docker until the migration is done.
- Update repo link for .repo command.
> Fix a few things in to-do

- userbot/modules/scrapers.py
this fix should last for a while until pytube devs update their docs.
PS : NEW TO GITHUB + still learning to make good PR's
> fixed .yt_dl thumbnail issue

- requirements.txt
- requirementsDOCKER.txt
- sample_config.env
- userbot/__init__.py
- userbot/modules/admin.py
- userbot/modules/afk.py
- userbot/modules/dbhelper.py
- userbot/modules/filter.py
- userbot/modules/notes.py
- userbot/modules/pmpermit.py
- userbot/modules/purge.py
- userbot/modules/scrapers.py
All commands was tested by me. Most files, that I've modified was linted via flake8.
> Rework commands to MongoDB & Redis

- userbot/modules/welcomes.py
Signed-off-by: Kandarp <Kandnub@gmail.com>
> [welcomes] Fix and add some checks

- userbot/modules/afk.py
Should fix mentions count while user's afk.
Signed-off-by: pqhaz <usaguy1342@gmail.com>
> modules: afk: Import USERS variable

- userbot/modules/userdata.py
signed off by: DrPhilosophus95 anwersha256@disroot.org
> Fixed typo

- userbot/modules/filter.py
- userbot/modules/notes.py
- userbot/modules/pmpermit.py
- userbot/modules/purge.py
- userbot/modules/spotify.py
- userbot/modules/updater.py
**filters:** Add missing await and make it save reply text as a filter.
**notes:** Stop the reply text note's first char getting cut.
**pmpermit:** Baal didn't merge it from staging so I thought why not?
**purge:** Remove self destruct warning from text for sd.
**spotify:** Handle bio too long exception.
**updater:** Send changelog as a file if it exceeds TG limit.
> Fixed minor errors reported by @IP1241

- userbot/modules/notes.py
Signed off by: Anwer anwersha256@disroot.org
> Fixed typo and get notes

- userbot/modules/dogbin.py
- userbot/modules/memes.py
- userbot/modules/pmpermit.py
- userbot/modules/qrcode.py
Signed-off-by: Kandarp <Kandnub@gmail.com>
> Fix: auto_approve check, enable runs, qrcode, dogbin

- userbot/modules/mute_chat.py
Doing PR for the first time so bear with me 
[Error Logs](https://del.dog/anebisocon)
This is the error
Idk how to do this
Hope this works
> Update mute_chat.py [Read Desc]

- requirements.txt
- userbot/modules/admin.py
- userbot/modules/scrapers.py
- userbot/modules/welcomes.py
* Fix issue #144 
* Fix yt_dl not working by forcing a newer update
* Make yt module throw error if API Key isn't found
* Fix error in welcome.py because of variable being referenced before assignment.
> Fix #144, yt_dl, more

- requirements.txt
- userbot/modules/kang.py
also update telethon because telethon 1.9 is able to handle animated stickers
Signed-off-by: rupansh-servur <rupanshsekar@hotmail.com>
> userbot: modules: kang: support kanging animated stickers

- userbot/modules/pmpermit.py
Deletes the previous UNAPPROVED_MSG when sending a new one.
> Non Spammy pmpermit

- Dockerfile
- requirements.txt
- userbot/modules/gen_direct_links.py
Inspired from t.me/android_helper_bot
Supports:
- Google Drive
- Yandex.Disk
- cloud.mail.ru
- ZippyShare
- MEGA.nz (need fix?)
**Note about MEGA:** I've tested the shell script on Ubuntu and Manjaro, it works perfectly. But, on userbot alpine container, it fails even with all dependencies installed (openssl - jq - pv) I'll try to dig in more.
This PR also adds pip packages caching to docker
> Direct links generator module

- Dockerfile
- userbot/modules/gen_direct_links.py
* unify different commands in one function to deal with telegram
* add type hints to scraping functions
* Fix docker pip packages caching
* Add MediaFire support
* Add SourceForge support
* Add OSDN support
* Add GitHub support
* Add AFH support
> gen_direct_links: refactor, Add more sites

- userbot/modules/android.py
This module can:
* Get Magisk latest downloads
* Get twrp latest download for a codename
* Get info about android device codename or model (name / brand)
* Search for android device codename
* Get mobile device specifications
Commands are:
```
.magisk
.twrp <codename>
.device <codename>
.codename <brand> <device>
.specs <brand> <device>
```
It works for replies too.
> Add Android module

- requirements.txt
- userbot/modules/download.py
Improves files download speed
Test URL [Here](https://cfhcable.dl.sourceforge.net/project/bootleggersrom//builds/whyred/BootleggersROM-Pie4whyred.4.2-Stable-Shishufied-20190711-094313.zip)
**Before:**
```
Downloaded to ./BootleggersROM-Pie4whyred.4.2-Stable-Shishufied-20190711-094313.zip in 524 seconds.
```
**After:**
```
Downloaded BootleggersROM-Pie4whyred.4.2-Stable-Shishufied-20190711-094313.zip in 40 seconds.
```
> download: use pyDownload for faster file downloads

- .gitignore
- generate_drive_session.py
- requirements.txt
- sample_config.env
- userbot/__init__.py
- userbot/modules/android.py
- userbot/modules/download.py
Downloads a file from telegram or link to the server then upload to your GDrive.
* Separate .download methods into download_from_url, download_from_tg
* Add gdrive_upload that handle Authentication and Upload process using PyDrive
* And gdrive function that deals with telegram stuff
It works for files from telegram or a URL
Usage:
```.mirror [in reply to TG file] or .mirror <link> | <filename>```
**Note:** User needs to do the following:
*  Visit the [Google Cloud Console](https://console.developers.google.com/apis/credentials)
* Go to the OAuth Consent tab, fill it, and save.
* Go to the Credentials tab and click Create Credentials -> OAuth Client ID
* Choose Other and Create.
* Use the download button to download your credentials.
* Move that file to the root of pydrive-client, and …
> Add Google Drive Mirror command

- requirements.txt
- userbot/modules/download.py
Handling files in memory is faster, improve code where i found it to be cancer. Might add a check for memory idk
> userbot: modules: rewrite gdrive upload

- Dockerfile
- userbot/modules/android.py
- userbot/modules/download.py
- userbot/modules/gen_direct_links.py
* gen_direct_links: fix few derps
* android: Add message header for magisk, device, and codename
* android: codename: limit results to 8
* android: specs: Add device name to message
* android: specs: Increase search results to two
* download: use async for download_from_url, gdrive_upload
* download: Add some more current status messages
* download: Add .drive command to upload files from the server
* download: fix some pylint warnings
> download, android, gen_direct_links: further improvements

- userbot/modules/afk.py
Signed-off-by: PainKiller3 <ninadpatil100@gmail.com>
> Afk: Fixed Afk Module Derp

- sample_config.env
- userbot/__init__.py
- userbot/modules/lastfm.py
- userbot/modules/spotify.py
Includes:
- .lastfm for a @lastfmrobot style status command
- .lastbio <on/off> to enable/disable showing now playing song in the users bio
- .lastlog <on/off> to enable/disable logging the bio updates to the users bot log
Changes:
- config.env - Added several variables for api access and the bio vars so this will break spotify if the user is dumb
- __init__ _ Same as above
- modules/spotify.py changed vars to reflect the config.env changes
> modules: added lastfm module

- userbot/modules/dbhelper.py
- userbot/modules/weather.py
> weather: Move weather city into db, minor bug fixes and polishment

- userbot/modules/afk.py
- userbot/modules/chat.py
- userbot/modules/fban_gban.py
- userbot/modules/filter.py
- userbot/modules/help.py
- userbot/modules/kang.py
- userbot/modules/lastfm.py
- userbot/modules/lists.py
- userbot/modules/misc.py
- userbot/modules/mute_chat.py
- userbot/modules/notes.py
- userbot/modules/pmpermit.py
- userbot/modules/purge.py
- userbot/modules/qrcode.py
- userbot/modules/scrapers.py
- userbot/modules/screencapture.py
- userbot/modules/sed.py
- userbot/modules/system_stats.py
- userbot/modules/updater.py
- userbot/modules/userdata.py
- userbot/modules/welcomes.py
- userbot/modules/whois.py
- userbot/modules/www.py
> treewide: Separate modules by commas in .help, refactor strings

- userbot/modules/updater.py
Match line 100 to line 45.
Fixes the following error:
AttributeError: 'Remote' object has no attribute 'git'
> fix minor derp ?

- userbot/modules/welcomes.py
- Cleanup [Kick = Ban + Unban]
- Don't say "kicking away" in welcome mute when not admin.
> welcome_mute - Improvements

- requirements.txt
- userbot/modules/scrapers.py
Fast, beautiful ...
and has description scraping too !!
> A new implementation of Google Search

- userbot/events.py
Should do the trick _**for now**_.
Signed-off-by: Kandarp <Kandnub@gmail.com>
> events: Fix incoming derp

- userbot/events.py
Silently log malicious inline bot behavior in console, instead of spamming the chat.
> events: silent security patch.

- README.md
apparently I never noticed my old username was here until someone checked yesterday, thanks @prkprime
> README: update username

- userbot/events.py
Fixes #232
Change-Id: I9b2b874717975a3b6d7d851fe8bed4b744299496
Signed-off-by: Akito Mizukito <akito@evolution-x.org>
> events: Log errors in BOTLOG if available

- userbot/modules/android.py
https://github.com/RaphielGang/Telegram-Paperplane/issues/236
Signed-off-by: yshalsager <ysh-alsager@hotmail.com>
> android: Fix .device and .codename commands

- sample_config.env
- userbot/__init__.py
- userbot/modules/scrapers.py
Request from *spoken* instead *full request* api nor wolframalpha module.
Aim for shorter, simple & avoid nonsense result.
> Add Wolfram module

- userbot/__init__.py
- userbot/events.py
- userbot/modules/lastfm.py
- userbot/modules/scrapers.py
Signed-off-by: Dhina17 <dhinalogu@gmail.com>
> Remove unused imports

- userbot/modules/admin.py
Change-Id: Id961491ae4dfd04a1acdf42b8d6823e5e2b18488
> promote: only grant permissions that we have ourselves

- userbot/modules/admin.py
* also call unmute to remove it from the database again
Change-Id: I5e7e66a3f74971f0eb5118c782e2457ef8d67d07
> admin: check if we can delete messages on mute fallback

- userbot/modules/android.py
* canary/*.json does not exist anymore
Change-Id: I60c66c4a633647eefc4f1bb13c9f5e708e3feb86
> android: fix magisk command

- userbot/modules/scrapers.py
* log error to BOTLOG channel if available
Change-Id: I308551c692a40ca2f21d28c7cabfa66551b7db18
> scrapers: google: catch NoResultsOrTrafficError exception
